spring:
  datasource:
    url: jdbc:h2:mem:saledb
    username: sa
    password:
  h2:
    console:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092

folder:
  source: sales/
  archive: sales_archive/